set_property PACKAGE_PIN M14 [get_ports data_out[0]]
set_property IOSTANDARD LVCMOS33 [get_ports data_out[0]]
set_property PACKAGE_PIN M15 [get_ports data_out[1]]
set_property IOSTANDARD LVCMOS33 [get_ports data_out[1]]
set_property PACKAGE_PIN G14 [get_ports data_out[2]]
set_property IOSTANDARD LVCMOS33 [get_ports data_out[2]]
set_property PACKAGE_PIN D18 [get_ports data_out[3]]
set_property IOSTANDARD LVCMOS33 [get_ports data_out[3]]
# Reset
set_property PACKAGE_PIN P16 [get_ports rst]
set_property IOSTANDARD LVCMOS33 [get_ports rst]
# clk
set_property PACKAGE_PIN R18 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
# wr
set_property PACKAGE_PIN Y16 [get_ports wr]
set_property IOSTANDARD LVCMOS33 [get_ports wr]
# rd
set_property PACKAGE_PIN V16 [get_ports rd]
set_property IOSTANDARD LVCMOS33 [get_ports rd]
# data_in[0]
set_property PACKAGE_PIN G15 [get_ports data_in[0]]
set_property IOSTANDARD LVCMOS33 [get_ports data_in[0]]
# data_in[1]
set_property PACKAGE_PIN P15 [get_ports data_in[1]]
set_property IOSTANDARD LVCMOS33 [get_ports data_in[1]]
# data_in[2]
set_property PACKAGE_PIN W13 [get_ports data_in[2]]
set_property IOSTANDARD LVCMOS33 [get_ports data_in[2]]
# data_in[3]
set_property PACKAGE_PIN T16 [get_ports data_in[3]]
set_property IOSTANDARD LVCMOS33 [get_ports data_in[3]]

set_property PACKAGE_PIN R14 [get_ports clr]
set_property IOSTANDARD LVCMOS33 [get_ports clr]

set_property PACKAGE_PIN U17 [get_ports fifo_cnt[0]]
set_property IOSTANDARD LVCMOS33 [get_ports fifo_cnt[0]]
set_property PACKAGE_PIN V13 [get_ports fifo_cnt[1]]
set_property IOSTANDARD LVCMOS33 [get_ports fifo_cnt[1]]
set_property PACKAGE_PIN H15 [get_ports fifo_cnt[2]]
set_property IOSTANDARD LVCMOS33 [get_ports fifo_cnt[2]]
set_property PACKAGE_PIN J15 [get_ports fifo_cnt[3]]
set_property IOSTANDARD LVCMOS33 [get_ports fifo_cnt[3]]
set_property PACKAGE_PIN W16 [get_ports full]
set_property IOSTANDARD LVCMOS33 [get_ports full]
set_property PACKAGE_PIN V12 [get_ports empty]
set_property IOSTANDARD LVCMOS33 [get_ports empty]

set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets clk_IBUF]